In [9]:
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"

In [10]:
# import nltk
# nltk.download('stopwords')

In [11]:
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'r

In [12]:
import lxml.html
input_file = 'inputs/19990609'

def read_file(input_file: str):
    html_text = ""
    with open(input_file, 'r', encoding="utf8") as f:
        for line in f:
            html_text += line
            
    return html_text
        
def strip_tag(html_text: str):
    return lxml.html.fromstring(html_text).text_content()


def strip_symbol(content: str):
    res = content.translate({ord(c): None for c in ("!@#$%^&*(),./;':\\|<>`~\"”“")})
    return res

def strip_all(html: str):
    content = strip_tag(html)
    content = strip_symbol(str(content).lower())
    return content
    

html_text = read_file(input_file)
content = strip_all(html_text)


def str2doc(content: str):
    return content.split()

document = str2doc(content)
document

['google',
 'and',
 'privacy',
 'this',
 'is',
 'an',
 'archived',
 'version',
 'of',
 'our',
 'privacy',
 'policy',
 'view',
 'the',
 'current',
 'version',
 'or',
 'all',
 'past',
 'versions',
 'google',
 'is',
 'sensitive',
 'to',
 'the',
 'privacy',
 'concerns',
 'of',
 'its',
 'users',
 'the',
 'internet',
 'allows',
 'individuals',
 'to',
 'explore',
 'and',
 'communicate',
 'with',
 'unprecedented',
 'ease',
 'but',
 'it',
 'also',
 'allows',
 'websites',
 'to',
 'collect',
 'and',
 'distribute',
 'personal',
 'information',
 'with',
 'equal',
 'ease',
 'we',
 'at',
 'google',
 'know',
 'that',
 'many',
 'users',
 'are',
 'understandably',
 'concerned',
 'about',
 'such',
 'practices',
 'and',
 'we',
 'wish',
 'to',
 'make',
 'clear',
 'our',
 'policy',
 'for',
 'collecting',
 'and',
 'using',
 'personal',
 'information',
 'google’s',
 'policy',
 'google’s',
 'policy',
 'on',
 'our',
 'wholly',
 'controlled',
 'and',
 'operated',
 'internet',
 'sites',
 'is',
 'to',
 'respect',


In [13]:
def filter_doc(document: list, stop_words: set):
    res = [word for word in document if word not in stop_words and not word.isdigit() and len(word) > 3]
    return res

document = filter_doc(document, stop_words)
document

['google',
 'privacy',
 'archived',
 'version',
 'privacy',
 'policy',
 'view',
 'current',
 'version',
 'past',
 'versions',
 'google',
 'sensitive',
 'privacy',
 'concerns',
 'users',
 'internet',
 'allows',
 'individuals',
 'explore',
 'communicate',
 'unprecedented',
 'ease',
 'also',
 'allows',
 'websites',
 'collect',
 'distribute',
 'personal',
 'information',
 'equal',
 'ease',
 'google',
 'know',
 'many',
 'users',
 'understandably',
 'concerned',
 'practices',
 'wish',
 'make',
 'clear',
 'policy',
 'collecting',
 'using',
 'personal',
 'information',
 'google’s',
 'policy',
 'google’s',
 'policy',
 'wholly',
 'controlled',
 'operated',
 'internet',
 'sites',
 'respect',
 'protect',
 'privacy',
 'users',
 'google',
 'willfully',
 'disclose',
 'individually',
 'identifiable',
 'information',
 'customers',
 'third',
 'party',
 'without',
 'first',
 'receiving',
 'customer’s',
 'permission',
 'policy',
 'statement',
 'tells',
 'collect',
 'information',
 'google',
 'share',
 'in

In [14]:
from lxml import etree
html_file = "Updates_ Privacy Policy – Privacy & Terms – Google.html"
html_text = ""
with open(html_file, 'r') as f:
    for line in f:
        html_text += line
        
html = lxml.html.fromstring(html_text)
html

<Element html at 0x7f0cbd21e9f8>

In [15]:
history_urls = html.xpath('//*[@id="archives"]/li/a/@href')
history_urls

['https://policies.google.com/privacy?hl=en&gl=CN',
 'https://policies.google.com/privacy/archive/20180525?hl=en&gl=CN',
 'https://policies.google.com/privacy/archive/20171218?hl=en&gl=CN',
 'https://www.google.com/intl/en_CN/policies/privacy/archive/20171002/',
 'https://www.google.com/intl/en_CN/policies/privacy/archive/20170417/',
 'https://www.google.com/intl/en_CN/policies/privacy/archive/20170301/',
 'https://www.google.com/intl/en_CN/policies/privacy/archive/20160829/',
 'https://www.google.com/intl/en_CN/policies/privacy/archive/20160628/',
 'https://www.google.com/intl/en_CN/policies/privacy/archive/20160325/',
 'https://www.google.com/intl/en_CN/policies/privacy/archive/20150819/',
 'https://www.google.com/intl/en_CN/policies/privacy/archive/20150630/',
 'https://www.google.com/intl/en_CN/policies/privacy/archive/20150605/',
 'https://www.google.com/intl/en_CN/policies/privacy/archive/20150501/',
 'https://www.google.com/intl/en_CN/policies/privacy/archive/20150225/',
 'https

In [16]:
type(history_urls)

list

In [17]:
import os
inputs = "inputs"
input_files = [os.path.join(inputs, input_file) for input_file in os.listdir(inputs)]
input_files.sort()
input_files

['inputs/19990609',
 'inputs/19990920',
 'inputs/20010104',
 'inputs/20040701',
 'inputs/20051014',
 'inputs/20080807',
 'inputs/20090127',
 'inputs/20090311',
 'inputs/20101003',
 'inputs/20111020',
 'inputs/20120301',
 'inputs/20120727',
 'inputs/20130624',
 'inputs/20131220',
 'inputs/20140331',
 'inputs/20141219',
 'inputs/20150225',
 'inputs/20150501',
 'inputs/20150605',
 'inputs/20150630',
 'inputs/20150819',
 'inputs/20160325',
 'inputs/20160628',
 'inputs/20160829',
 'inputs/20170301',
 'inputs/20170417',
 'inputs/20171002']

In [18]:
time_seq = []
years = [input_file[-8: -4] for input_file in input_files]
# years
from collections import Counter
years_count = Counter(years)
years = list(set(years))
years.sort()
time_seq = [years_count[year] for year in years]
years_count
# time_seq.append(1)

Counter({'1999': 2,
         '2001': 1,
         '2004': 1,
         '2005': 1,
         '2008': 1,
         '2009': 2,
         '2010': 1,
         '2011': 1,
         '2012': 2,
         '2013': 2,
         '2014': 2,
         '2015': 5,
         '2016': 3,
         '2017': 3})

In [19]:
documents = []
for file in input_files:
    try:
        html_text = read_file(file)
        content = strip_all(html_text)
        document = str2doc(content)
        documents.append(filter_doc(document, stop_words))
        print(file)
    except:
        pass

# documents.append(["test"])
len(documents)
[len(document) for document in documents]
from pprint import pprint
# pprint(documents)

inputs/19990609
inputs/19990920
inputs/20010104
inputs/20040701
inputs/20051014
inputs/20080807
inputs/20090127
inputs/20090311
inputs/20101003
inputs/20111020
inputs/20120301
inputs/20120727
inputs/20130624
inputs/20131220
inputs/20140331
inputs/20141219
inputs/20150225
inputs/20150501
inputs/20150605
inputs/20150630
inputs/20150819
inputs/20160325
inputs/20160628
inputs/20160829
inputs/20170301
inputs/20170417
inputs/20171002


27

[323,
 322,
 341,
 521,
 952,
 1010,
 1027,
 1112,
 864,
 894,
 1179,
 1180,
 1182,
 1186,
 1694,
 1862,
 1969,
 1956,
 2034,
 2035,
 2055,
 2075,
 2157,
 2165,
 2163,
 2164,
 2171]

In [20]:
time_seq = [2, 2, 3] # total 7 documents; 2 for first, 2 for second and 3 for the last
import os
from gensim import corpora, utils
from gensim.models.wrappers.dtmmodel import DtmModel
import numpy as np

In [21]:
class DTMcorpus(corpora.textcorpus.TextCorpus):

    def get_texts(self):
        return self.input

    def __len__(self):
        return len(self.input)

corpus = DTMcorpus(documents)
len(corpus)

27

In [22]:
time_seq = [1 for i in range(len(corpus))]

In [23]:
path_to_dtm_binary = "./dtm-linux64"
model = DtmModel(path_to_dtm_binary, corpus, time_seq, num_topics=1,
                 id2word=corpus.dictionary, initialize_lda=True)

In [24]:
topics = model.show_topic(topicid=0, time=0, topn=10)
topics

[(0.05167127636507331, 'information'),
 (0.04728179814421867, 'google'),
 (0.024155757398757027, 'privacy'),
 (0.023199986307747045, 'services'),
 (0.021887781441777915, 'policy'),
 (0.02046060208813379, 'personal'),
 (0.012753369691468215, 'cookies'),
 (0.010360323400955648, 'provide'),
 (0.00885865053839998, 'search'),
 (0.008525510287103638, 'data')]

In [25]:
for i in range(1):
    for j in range(len(time_seq)):
        print(input_files[j].split("/")[-1] + ":")
        model.show_topic(i, j, 10)

19990609:


[(0.05167127636507331, 'information'),
 (0.04728179814421867, 'google'),
 (0.024155757398757027, 'privacy'),
 (0.023199986307747045, 'services'),
 (0.021887781441777915, 'policy'),
 (0.02046060208813379, 'personal'),
 (0.012753369691468215, 'cookies'),
 (0.010360323400955648, 'provide'),
 (0.00885865053839998, 'search'),
 (0.008525510287103638, 'data')]

19990920:


[(0.05231718285445513, 'information'),
 (0.04623714311533394, 'google'),
 (0.02458663664207228, 'privacy'),
 (0.023683162191572453, 'services'),
 (0.021921756595229838, 'policy'),
 (0.02063807531440133, 'personal'),
 (0.012573191561840207, 'cookies'),
 (0.010479197516807882, 'provide'),
 (0.008716894761938442, 'search'),
 (0.008568005768206068, 'data')]

20010104:


[(0.05327517535374507, 'information'),
 (0.04419201168797691, 'google'),
 (0.025326788238758953, 'privacy'),
 (0.024528263507167445, 'services'),
 (0.021916115292637935, 'policy'),
 (0.021120161478535533, 'personal'),
 (0.01220214754176721, 'cookies'),
 (0.01067176308294965, 'provide'),
 (0.008661000207995683, 'data'),
 (0.008340929444458838, 'search')]

20040701:


[(0.054261018274825636, 'information'),
 (0.04166227833306786, 'google'),
 (0.026299248516814498, 'privacy'),
 (0.025638359826148593, 'services'),
 (0.021988666676352225, 'personal'),
 (0.02183933827311717, 'policy'),
 (0.01167187045817131, 'cookies'),
 (0.010884504252910564, 'provide'),
 (0.008776723453031548, 'data'),
 (0.007759554426855692, 'search')]

20051014:


[(0.0548495433698057, 'information'),
 (0.03946239441463337, 'google'),
 (0.02737996919767484, 'privacy'),
 (0.026866414936562225, 'services'),
 (0.02303533858617258, 'personal'),
 (0.021653166022187493, 'policy'),
 (0.011099498876111837, 'cookies'),
 (0.011024867453556329, 'provide'),
 (0.008855366279226137, 'data'),
 (0.007894354921353739, 'access')]

20080807:


[(0.05519029503947297, 'information'),
 (0.03794853744350726, 'google'),
 (0.02830393771121987, 'privacy'),
 (0.028106122251199954, 'services'),
 (0.023487769063130503, 'personal'),
 (0.021281168581813652, 'policy'),
 (0.011014532725976411, 'provide'),
 (0.010624618631865927, 'cookies'),
 (0.008825968398310957, 'data'),
 (0.008179219288769168, 'access')]

20090127:


[(0.05561764491223209, 'information'),
 (0.03715124385479757, 'google'),
 (0.029263800515438445, 'services'),
 (0.028540097657208257, 'privacy'),
 (0.023074499247080927, 'personal'),
 (0.020671852740974845, 'policy'),
 (0.010834609643076174, 'provide'),
 (0.010239926420743823, 'cookies'),
 (0.008667970478381496, 'data'),
 (0.008443332972579593, 'access')]

20090311:


[(0.05637125320387888, 'information'),
 (0.03689898480882528, 'google'),
 (0.030236563708967375, 'services'),
 (0.02789710106732794, 'privacy'),
 (0.021843793695133125, 'personal'),
 (0.019811214483002444, 'policy'),
 (0.01050044409536562, 'provide'),
 (0.00991836462571795, 'cookies'),
 (0.008675062006825052, 'access'),
 (0.008376565818453023, 'data')]

20101003:


[(0.05764208106508307, 'information'),
 (0.036838998146728544, 'google'),
 (0.030907039010410454, 'services'),
 (0.026510151825919582, 'privacy'),
 (0.020118838905417186, 'personal'),
 (0.018723105717477193, 'policy'),
 (0.010057506054155759, 'provide'),
 (0.009623074762225473, 'cookies'),
 (0.008862560607914365, 'access'),
 (0.008491030023818937, 'account')]

20111020:


[(0.05939691055479443, 'information'),
 (0.03666641557553568, 'google'),
 (0.03120712777737882, 'services'),
 (0.024793717067115816, 'privacy'),
 (0.018459901888903025, 'personal'),
 (0.01748811141605285, 'policy'),
 (0.009570566158826448, 'provide'),
 (0.00932119435529309, 'cookies'),
 (0.009152752050770261, 'account'),
 (0.008976685795249658, 'access')]

20120301:


[(0.061238654346486183, 'information'),
 (0.036386590481022815, 'google'),
 (0.03111647738153352, 'services'),
 (0.023023197096770007, 'privacy'),
 (0.017009096079818226, 'personal'),
 (0.016203529855081635, 'policy'),
 (0.009840394594969607, 'account'),
 (0.009080529141131548, 'provide'),
 (0.009014314108635704, 'cookies'),
 (0.009012569884430131, 'access')]

20120727:


[(0.06220135234742199, 'information'),
 (0.03629379832023179, 'google'),
 (0.03065439807916287, 'services'),
 (0.021401663045952885, 'privacy'),
 (0.015817836085446672, 'personal'),
 (0.014990106339745417, 'policy'),
 (0.010496149058751026, 'account'),
 (0.010425095161525332, 'example'),
 (0.009082535100067651, 'including'),
 (0.008985752306907365, 'access')]

20130624:


[(0.06184074597008758, 'information'),
 (0.03655544182571471, 'google'),
 (0.02988146073581468, 'services'),
 (0.01996725015864642, 'privacy'),
 (0.014817786768340693, 'personal'),
 (0.013884952984018041, 'policy'),
 (0.01260677852346941, 'example'),
 (0.011105174557332897, 'account'),
 (0.00937582112822418, 'including'),
 (0.009066029022493175, 'collect')]

20131220:


[(0.06016164900486564, 'information'),
 (0.03723339871616336, 'google'),
 (0.028887050501335797, 'services'),
 (0.01869487207494375, 'privacy'),
 (0.01546475582100744, 'example'),
 (0.013935792395932524, 'personal'),
 (0.01288890827077116, 'policy'),
 (0.011674734605946197, 'account'),
 (0.009566875106137546, 'including'),
 (0.00916902959582556, 'collect')]

20140331:


[(0.05760706711014169, 'information'),
 (0.03828409605924982, 'google'),
 (0.027792881048816827, 'services'),
 (0.019065874030752387, 'example'),
 (0.017558305383662185, 'privacy'),
 (0.013148350093590003, 'personal'),
 (0.012219351849432764, 'account'),
 (0.011998504600525048, 'policy'),
 (0.009668117867784931, 'including'),
 (0.009162330664030688, 'collect')]

20141219:


[(0.05509101382630492, 'information'),
 (0.03957272854283861, 'google'),
 (0.026773730145278837, 'services'),
 (0.023006778173432066, 'example'),
 (0.0165733255873, 'privacy'),
 (0.012753575074286429, 'account'),
 (0.012523890892869696, 'personal'),
 (0.01123008986783862, 'policy'),
 (0.009710820389686417, 'including'),
 (0.009554997426952956, 'learn')]

20150225:


[(0.053052451190033635, 'information'),
 (0.040957780486705925, 'google'),
 (0.02650815682991161, 'example'),
 (0.025933866566503903, 'services'),
 (0.015758070483428067, 'privacy'),
 (0.013282306973104965, 'account'),
 (0.012036666597263778, 'personal'),
 (0.010905500633609662, 'learn'),
 (0.01059552922492322, 'policy'),
 (0.009700325531235137, 'including')]

20150501:


[(0.05158241125115935, 'information'),
 (0.04223114631413285, 'google'),
 (0.02917399758663952, 'example'),
 (0.025319456165161867, 'services'),
 (0.015121521627082048, 'privacy'),
 (0.013783160209794029, 'account'),
 (0.01205419152749158, 'learn'),
 (0.011658825081958943, 'personal'),
 (0.010091798887739116, 'policy'),
 (0.00965845676636254, 'including')]

20150605:


[(0.050666833221978846, 'information'),
 (0.04323639584568597, 'google'),
 (0.03095199454361519, 'example'),
 (0.024930061501287307, 'services'),
 (0.014660049828811205, 'privacy'),
 (0.014242342133788258, 'account'),
 (0.013008012944736394, 'learn'),
 (0.01137072547999586, 'personal'),
 (0.00970319119945418, 'policy'),
 (0.009599691956826353, 'including')]

20150630:


[(0.050083854135878104, 'information'),
 (0.04395835104145521, 'google'),
 (0.03193339022367215, 'example'),
 (0.024753818628502188, 'services'),
 (0.01462498820019104, 'account'),
 (0.014356815195185854, 'privacy'),
 (0.013756066993228231, 'learn'),
 (0.011150130027590908, 'personal'),
 (0.009541072539397039, 'including'),
 (0.00940785289119479, 'policy')]

20150819:


[(0.04963768049903025, 'information'),
 (0.04445431478240439, 'google'),
 (0.03235077457328393, 'example'),
 (0.024757368069803352, 'services'),
 (0.014933438760227782, 'account'),
 (0.014285052017322395, 'learn'),
 (0.014175736446802473, 'privacy'),
 (0.010984555027414331, 'personal'),
 (0.009490211612773629, 'including'),
 (0.009184445859639002, 'policy')]

20160325:


[(0.049221534114029755, 'information'),
 (0.04478777085213955, 'google'),
 (0.032448081001348494, 'example'),
 (0.02489080052617342, 'services'),
 (0.015182274794248012, 'account'),
 (0.01463457290352969, 'learn'),
 (0.01406971368194547, 'privacy'),
 (0.010879522155382165, 'personal'),
 (0.009451162893533158, 'including'),
 (0.009015328211666352, 'policy')]

20160628:


[(0.04881931232532743, 'information'),
 (0.04499699243917114, 'google'),
 (0.032411284216885716, 'example'),
 (0.02509905612017472, 'services'),
 (0.015373440540293748, 'account'),
 (0.01485744510194817, 'learn'),
 (0.014012676557458302, 'privacy'),
 (0.0108258372829353, 'personal'),
 (0.009427470677952726, 'including'),
 (0.008888552152951338, 'policy')]

20160829:


[(0.048499951445775354, 'information'),
 (0.045070181572295955, 'google'),
 (0.03235615352312647, 'example'),
 (0.025325842671119963, 'services'),
 (0.015507229974226773, 'account'),
 (0.01499942471855476, 'learn'),
 (0.013993543992894378, 'privacy'),
 (0.010796576114760615, 'personal'),
 (0.009422986757731797, 'including'),
 (0.008798205106016338, 'policy')]

20170301:


[(0.048282853409882975, 'information'),
 (0.045053939845171836, 'google'),
 (0.03232702988520865, 'example'),
 (0.0255338085385025, 'services'),
 (0.015595231803233188, 'account'),
 (0.015090450230700738, 'learn'),
 (0.013994379122230234, 'privacy'),
 (0.010779839787247485, 'personal'),
 (0.009427793988877229, 'including'),
 (0.008738198196824514, 'policy')]

20170417:


[(0.048154238468847976, 'information'),
 (0.045025705658381425, 'google'),
 (0.032322251254327174, 'example'),
 (0.025694458420060965, 'services'),
 (0.015648304617998925, 'account'),
 (0.015145253427370586, 'learn'),
 (0.01400268264384605, 'privacy'),
 (0.010769896461759089, 'personal'),
 (0.00943525647452593, 'including'),
 (0.008702525969229514, 'policy')]

20171002:


[(0.048095953918806465, 'information'),
 (0.04501719094368398, 'google'),
 (0.03232708916514276, 'example'),
 (0.025784767134149966, 'services'),
 (0.015674086895607033, 'account'),
 (0.01517153319603991, 'learn'),
 (0.014009824596869917, 'privacy'),
 (0.010764948305510206, 'personal'),
 (0.009440834557300413, 'including'),
 (0.008712569583148077, 'like')]

In [26]:
model.gamma_

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [27]:
dim_model = DtmModel(path_to_dtm_binary, corpus, time_seq, num_topics=1,
                 id2word=corpus.dictionary, initialize_lda=True, model='fixed')

In [28]:
document_no = 1 #document 2
topic_no = 0 #topic number 1
time_slice = 0 #time slice 1

type(dim_model.influences_time)
dim_model.influences_time

# for document_no in range(len(corpus)):
# for time_slice in range(len(time_seq)):
#    dim_model.influences_time[time_slice][document_no][topic_no]
    

list

[array([[0.04487017]]),
 array([[0.00755651]]),
 array([[0.01054809]]),
 array([[0.03098739]]),
 array([[0.08948956]]),
 array([[0.00262296]]),
 array([[-0.00572049]]),
 array([[0.02206943]]),
 array([[-0.00018109]]),
 array([[0.04982455]]),
 array([[0.09681206]]),
 array([[0.02833254]]),
 array([[-0.01311693]]),
 array([[-0.02827837]]),
 array([[0.04643593]]),
 array([[0.07417891]]),
 array([[0.04799896]]),
 array([[0.02677942]]),
 array([[0.04160749]]),
 array([[0.03504583]]),
 array([[0.04164879]]),
 array([[0.03966195]]),
 array([[0.03814424]]),
 array([[0.02960172]]),
 array([[0.01487303]]),
 array([[0.00038175]]),
 array([[0.]])]

In [29]:
help(dim_model)

Help on DtmModel in module gensim.models.wrappers.dtmmodel object:

class DtmModel(gensim.utils.SaveLoad)
 |  Python wrapper using `DTM implementation <https://github.com/magsilva/dtm/tree/master/bin>`_.
 |  
 |  Communication between DTM and Python takes place by passing around data files on disk and executing
 |  the DTM binary as a subprocess.
 |  
 |  Warnings
 |  --------
 |  This is **only** python wrapper for `DTM implementation <https://github.com/magsilva/dtm/tree/master/bin>`_,
 |  you need to install original implementation first and pass the path to binary to ``dtm_path``.
 |  
 |  Method resolution order:
 |      DtmModel
 |      gensim.utils.SaveLoad
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(self, dtm_path, corpus=None, time_slices=None, mode='fit', model='dtm', num_topics=100, id2word=None, prefix=None, lda_sequence_min_iter=6, lda_sequence_max_iter=20, lda_max_em_iter=10, alpha=0.01, top_chain_var=0.005, rng_seed=0, initialize_lda=True)
 |

In [30]:
influences = [round(max(i)[0], 4) for i in dim_model.influences_time]
influences

[0.0449,
 0.0076,
 0.0105,
 0.031,
 0.0895,
 0.0026,
 -0.0057,
 0.0221,
 -0.0002,
 0.0498,
 0.0968,
 0.0283,
 -0.0131,
 -0.0283,
 0.0464,
 0.0742,
 0.048,
 0.0268,
 0.0416,
 0.035,
 0.0416,
 0.0397,
 0.0381,
 0.0296,
 0.0149,
 0.0004,
 0.0]

In [51]:
from pyecharts import Line

line = Line("Influences")
years = [i for i in range(len(influences))]
line.add("Google's policies", years, influences, mark_point=['max'], 
         mark_point_symbol='arrow', mark_point_symbolsize=65,
        xaxis_name="version", yaxis_name="influence",
        yaxis_name_gap=45)

In [32]:
test_documents = [documents[4] for i in range(10)]
test_corpus = DTMcorpus(test_documents)
test_time_seq = [1] * 10
test_dim_model = DtmModel(path_to_dtm_binary, test_corpus, test_time_seq, num_topics=1,
                 id2word=test_corpus.dictionary, initialize_lda=True, model='fixed')

In [33]:
test_dim_model.influences_time

[array([[0.38547742]]),
 array([[0.15435206]]),
 array([[0.05475012]]),
 array([[0.02807272]]),
 array([[0.02779628]]),
 array([[0.02951287]]),
 array([[0.02450806]]),
 array([[0.01139932]]),
 array([[0.00020762]]),
 array([[0.]])]

# Confused

Why `influences_time` varies with exactly **identical** documents?
And it decreases?

# Possible Explanation

`time slice` may be taken into consideration

# According the paper

## Screenshots:

---
<img src="https://ws4.sinaimg.cn/large/006tKfTcgy1g0ogsc25abj30ry05cgmx.jpg" width="400px"/>

---
<img src="https://ws2.sinaimg.cn/large/006tKfTcgy1g0ogziwu7zj30yo07qmyq.jpg" width="400dip"/>

where $\tilde{m}_{t+1}$ stands for the mean value of topic trajectory $\tilde{\beta}_{k, t}$.