In [1]:
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"

In [2]:
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'r

In [3]:
import lxml.html
input_file = 'inputs/19990609'

def read_file(input_file: str):
    html_text = ""
    with open(input_file, 'r') as f:
        for line in f:
            html_text += line
            
    return html_text
        
def strip_tag(html_text: str):
    return lxml.html.fromstring(html_text).text_content()


def strip_symbol(content: str):
    res = content.translate({ord(c): None for c in ("!@#$%^&*(),./;':\\|<>`~\"”“")})
    return res

def strip_all(html: str):
    content = strip_tag(html)
    content = strip_symbol(str(content).lower())
    return content
    

html_text = read_file(input_file)
content = strip_all(html_text)


def str2doc(content: str):
    return content.split()

document = str2doc(content)

In [4]:
def filter_doc(document: list, stop_words: set):
    res = [word for word in document if word not in stop_words and not word.isdigit() and len(word) > 3]
    return res

document = filter_doc(document, stop_words)
document

['google',
 'privacy',
 'archived',
 'version',
 'privacy',
 'policy',
 'view',
 'current',
 'version',
 'past',
 'versions',
 'google',
 'sensitive',
 'privacy',
 'concerns',
 'users',
 'internet',
 'allows',
 'individuals',
 'explore',
 'communicate',
 'unprecedented',
 'ease',
 'also',
 'allows',
 'websites',
 'collect',
 'distribute',
 'personal',
 'information',
 'equal',
 'ease',
 'google',
 'know',
 'many',
 'users',
 'understandably',
 'concerned',
 'practices',
 'wish',
 'make',
 'clear',
 'policy',
 'collecting',
 'using',
 'personal',
 'information',
 'google’s',
 'policy',
 'google’s',
 'policy',
 'wholly',
 'controlled',
 'operated',
 'internet',
 'sites',
 'respect',
 'protect',
 'privacy',
 'users',
 'google',
 'willfully',
 'disclose',
 'individually',
 'identifiable',
 'information',
 'customers',
 'third',
 'party',
 'without',
 'first',
 'receiving',
 'customer’s',
 'permission',
 'policy',
 'statement',
 'tells',
 'collect',
 'information',
 'google',
 'share',
 'in

In [5]:
from lxml import etree
html_file = "Updates_ Privacy Policy – Privacy & Terms – Google.html"
html_text = ""
with open(html_file, 'r') as f:
    for line in f:
        html_text += line
        
html = lxml.html.fromstring(html_text)
html

<Element html at 0x122e139f8>

In [6]:
history_urls = html.xpath('//*[@id="archives"]/li/a/@href')
history_urls

['https://policies.google.com/privacy?hl=en&gl=CN',
 'https://policies.google.com/privacy/archive/20180525?hl=en&gl=CN',
 'https://policies.google.com/privacy/archive/20171218?hl=en&gl=CN',
 'https://www.google.com/intl/en_CN/policies/privacy/archive/20171002/',
 'https://www.google.com/intl/en_CN/policies/privacy/archive/20170417/',
 'https://www.google.com/intl/en_CN/policies/privacy/archive/20170301/',
 'https://www.google.com/intl/en_CN/policies/privacy/archive/20160829/',
 'https://www.google.com/intl/en_CN/policies/privacy/archive/20160628/',
 'https://www.google.com/intl/en_CN/policies/privacy/archive/20160325/',
 'https://www.google.com/intl/en_CN/policies/privacy/archive/20150819/',
 'https://www.google.com/intl/en_CN/policies/privacy/archive/20150630/',
 'https://www.google.com/intl/en_CN/policies/privacy/archive/20150605/',
 'https://www.google.com/intl/en_CN/policies/privacy/archive/20150501/',
 'https://www.google.com/intl/en_CN/policies/privacy/archive/20150225/',
 'https

In [7]:
type(history_urls)

list

In [8]:
import os
inputs = "inputs"
input_files = [os.path.join(inputs, input_file) for input_file in os.listdir(inputs)]
input_files.sort()
input_files

['inputs/19990609',
 'inputs/19990920',
 'inputs/20010104',
 'inputs/20040701',
 'inputs/20051014',
 'inputs/20080807',
 'inputs/20090127',
 'inputs/20090311',
 'inputs/20101003',
 'inputs/20111020',
 'inputs/20120301',
 'inputs/20120727',
 'inputs/20130624',
 'inputs/20131220',
 'inputs/20140331',
 'inputs/20141219',
 'inputs/20150225',
 'inputs/20150501',
 'inputs/20150605',
 'inputs/20150630',
 'inputs/20150819',
 'inputs/20160325',
 'inputs/20160628',
 'inputs/20160829',
 'inputs/20170301',
 'inputs/20170417',
 'inputs/20171002']

In [9]:
time_seq = []
years = [input_file[-8: -4] for input_file in input_files]
# years
from collections import Counter
years_count = Counter(years)
years = list(set(years))
years.sort()
time_seq = [years_count[year] for year in years]
years_count
# time_seq.append(1)

Counter({'1999': 2,
         '2001': 1,
         '2004': 1,
         '2005': 1,
         '2008': 1,
         '2009': 2,
         '2010': 1,
         '2011': 1,
         '2012': 2,
         '2013': 2,
         '2014': 2,
         '2015': 5,
         '2016': 3,
         '2017': 3})

In [10]:
documents = []
for file in input_files:
    html_text = read_file(file)
    content = strip_all(html_text)
    document = str2doc(content)
    documents.append(filter_doc(document, stop_words))

# documents.append(["test"])
len(documents)
[len(document) for document in documents]
from pprint import pprint
# pprint(documents)

27

[323,
 322,
 341,
 521,
 952,
 1010,
 1027,
 1112,
 864,
 894,
 1179,
 1180,
 1182,
 1186,
 1694,
 1862,
 1969,
 1956,
 2034,
 2035,
 2055,
 2075,
 2157,
 2165,
 2163,
 2164,
 2171]

In [11]:
time_seq = [2, 2, 3] # total 7 documents; 2 for first, 2 for second and 3 for the last
import os
from gensim import corpora, utils
from gensim.models.wrappers.dtmmodel import DtmModel
import numpy as np

In [12]:
class DTMcorpus(corpora.textcorpus.TextCorpus):

    def get_texts(self):
        return self.input

    def __len__(self):
        return len(self.input)

corpus = DTMcorpus(documents)
len(corpus)

27

In [13]:
time_seq = [1 for i in range(len(corpus))]

In [14]:
path_to_dtm_binary = "./dtm-darwin64"
model = DtmModel(path_to_dtm_binary, corpus, time_seq, num_topics=1,
                 id2word=corpus.dictionary, initialize_lda=True)

In [15]:
topics = model.show_topic(topicid=0, time=0, topn=10)
topics

[(0.05170207854635812, 'information'),
 (0.04740395705736623, 'google'),
 (0.02343576472049303, 'privacy'),
 (0.023218525544327424, 'services'),
 (0.02185533966186131, 'policy'),
 (0.02038793818232774, 'personal'),
 (0.012728120676553089, 'cookies'),
 (0.010372833003486409, 'provide'),
 (0.008867910286899414, 'search'),
 (0.008536922748045158, 'data')]

In [16]:
for i in range(1):
    for j in range(len(time_seq)):
        print(input_files[j].split("/")[-1] + ":")
        model.show_topic(i, j, 10)

19990609:


[(0.05170207854635812, 'information'),
 (0.04740395705736623, 'google'),
 (0.02343576472049303, 'privacy'),
 (0.023218525544327424, 'services'),
 (0.02185533966186131, 'policy'),
 (0.02038793818232774, 'personal'),
 (0.012728120676553089, 'cookies'),
 (0.010372833003486409, 'provide'),
 (0.008867910286899414, 'search'),
 (0.008536922748045158, 'data')]

19990920:


[(0.052373381030124476, 'information'),
 (0.04633369562442682, 'google'),
 (0.0239086431642587, 'privacy'),
 (0.023701882935210753, 'services'),
 (0.021893453948065973, 'policy'),
 (0.020515270351871274, 'personal'),
 (0.012549521277511664, 'cookies'),
 (0.010491355484645665, 'provide'),
 (0.008725422694271725, 'search'),
 (0.008577531650975107, 'data')]

20010104:


[(0.053364870100181816, 'information'),
 (0.04423621197452928, 'google'),
 (0.024728905666645498, 'privacy'),
 (0.0245461442125542, 'services'),
 (0.021894573323109574, 'policy'),
 (0.020959406567880163, 'personal'),
 (0.012185436745132831, 'cookies'),
 (0.01068266223171738, 'provide'),
 (0.008668898281550583, 'data'),
 (0.008348161151134806, 'search')]

20040701:


[(0.05436467774394938, 'information'),
 (0.04164097886433799, 'google'),
 (0.02585269334177613, 'privacy'),
 (0.025651772277761994, 'services'),
 (0.02186391704532256, 'personal'),
 (0.02182506979920219, 'policy'),
 (0.011671921241861616, 'cookies'),
 (0.010892205414965554, 'provide'),
 (0.008783079195400131, 'data'),
 (0.0077646647707025635, 'search')]

20051014:


[(0.054908183942053185, 'information'),
 (0.03939688410031317, 'google'),
 (0.027198177900460703, 'privacy'),
 (0.026870382191458455, 'services'),
 (0.023036264291387117, 'personal'),
 (0.021645577487275098, 'policy'),
 (0.011114679553722123, 'cookies'),
 (0.01102732584351851, 'provide'),
 (0.008859387537140143, 'data'),
 (0.007897005822912638, 'access')]

20080807:


[(0.055167152223417365, 'information'),
 (0.03787247235844962, 'google'),
 (0.028466321612283147, 'privacy'),
 (0.028099848369332766, 'services'),
 (0.023565713538131895, 'personal'),
 (0.021279810659316088, 'policy'),
 (0.011012090762144953, 'provide'),
 (0.010637756699719529, 'cookies'),
 (0.008826708048803587, 'data'),
 (0.008179209131006214, 'access')]

20090127:


[(0.055519557912715366, 'information'),
 (0.0370990533149999, 'google'),
 (0.029253350627996666, 'services'),
 (0.028881544769505278, 'privacy'),
 (0.023162061231061657, 'personal'),
 (0.02067826982399923, 'policy'),
 (0.010830430070196377, 'provide'),
 (0.0102453505431373, 'cookies'),
 (0.008667678963003064, 'data'),
 (0.00844210876973902, 'access')]

20090311:


[(0.05623264792890052, 'information'),
 (0.0368939472421249, 'google'),
 (0.03022987286152491, 'services'),
 (0.028179649813337503, 'privacy'),
 (0.02188209996272668, 'personal'),
 (0.019825671188083212, 'policy'),
 (0.010497933055409388, 'provide'),
 (0.009916451851256808, 'cookies'),
 (0.008674769228376686, 'access'),
 (0.008378012850610789, 'data')]

20101003:


[(0.057518729166491554, 'information'),
 (0.036880055514647785, 'google'),
 (0.030908927941643474, 'services'),
 (0.02656886323159088, 'privacy'),
 (0.020080498849040573, 'personal'),
 (0.01874248827614072, 'policy'),
 (0.0100582783587155, 'provide'),
 (0.00961725749691335, 'cookies'),
 (0.008864622835512013, 'access'),
 (0.00845798860796072, 'account')]

20111020:


[(0.05934583061025046, 'information'),
 (0.03672555481737089, 'google'),
 (0.031213942548916296, 'services'),
 (0.02465962904242076, 'privacy'),
 (0.0184009654407863, 'personal'),
 (0.017506172492059494, 'policy'),
 (0.009573086847595544, 'provide'),
 (0.009315633801425614, 'cookies'),
 (0.009150498894999555, 'account'),
 (0.008980006390851456, 'access')]

20120301:


[(0.0613010053873633, 'information'),
 (0.03643568606208242, 'google'),
 (0.03112388287555434, 'services'),
 (0.02278708000566524, 'privacy'),
 (0.016966102417994487, 'personal'),
 (0.016216421233512798, 'policy'),
 (0.009866428459453154, 'account'),
 (0.009083252705039669, 'provide'),
 (0.009015902340835385, 'access'),
 (0.009011583299838215, 'cookies')]

20120727:


[(0.06234303117822188, 'information'),
 (0.0363222542452417, 'google'),
 (0.030659205968242103, 'services'),
 (0.02117036562631149, 'privacy'),
 (0.01581112232870957, 'personal'),
 (0.014998014034593691, 'policy'),
 (0.010530352438272965, 'account'),
 (0.010342867918980873, 'example'),
 (0.009082110660037074, 'including'),
 (0.0089881872623115, 'access')]

20130624:


[(0.0619964790301147, 'information'),
 (0.036564886046659646, 'google'),
 (0.029884345046595345, 'services'),
 (0.01979565479508816, 'privacy'),
 (0.014841996652788198, 'personal'),
 (0.013889504504869466, 'policy'),
 (0.012543233895939082, 'example'),
 (0.011126642764538647, 'account'),
 (0.009373732529681269, 'including'),
 (0.009058549572685703, 'collect')]

20131220:


[(0.06026663859181569, 'information'),
 (0.0372324969486672, 'google'),
 (0.028891031745047906, 'services'),
 (0.018584741834064066, 'privacy'),
 (0.015396280525797494, 'example'),
 (0.013969718341840994, 'personal'),
 (0.012891508616070926, 'policy'),
 (0.0116715847604895, 'account'),
 (0.009562028194648648, 'including'),
 (0.009164841212196597, 'collect')]

20140331:


[(0.05762647240963009, 'information'),
 (0.03828334879507095, 'google'),
 (0.02780054061056166, 'services'),
 (0.018940587081452284, 'example'),
 (0.017483168174724346, 'privacy'),
 (0.013171608160585657, 'personal'),
 (0.012192672351620474, 'account'),
 (0.011999909815189263, 'policy'),
 (0.00966115451116651, 'including'),
 (0.009164180947994188, 'collect')]

20141219:


[(0.05505288892969461, 'information'),
 (0.039578858551934507, 'google'),
 (0.02678476441489113, 'services'),
 (0.022807850939209385, 'example'),
 (0.016517365351710556, 'privacy'),
 (0.012716603700270593, 'account'),
 (0.012543504525880825, 'personal'),
 (0.011231067673365085, 'policy'),
 (0.0097049710470955, 'including'),
 (0.00959297975294978, 'learn')]

20150225:


[(0.05299492618525315, 'information'),
 (0.04097164325592383, 'google'),
 (0.026307401316236732, 'example'),
 (0.025945193899365677, 'services'),
 (0.01571032583580174, 'privacy'),
 (0.013250961299985433, 'account'),
 (0.012054458413567804, 'personal'),
 (0.010929967274551065, 'learn'),
 (0.010596126516293523, 'policy'),
 (0.009695577141964371, 'including')]

20150501:


[(0.051533718271182714, 'information'),
 (0.0422469481753091, 'google'),
 (0.029045594641623994, 'example'),
 (0.02532825831663604, 'services'),
 (0.015076883137292845, 'privacy'),
 (0.013765860098728707, 'account'),
 (0.012053807367415717, 'learn'),
 (0.011673280274515913, 'personal'),
 (0.01009203124071152, 'policy'),
 (0.00965448474616833, 'including')]

20150605:


[(0.05064752886577626, 'information'),
 (0.04324589615284377, 'google'),
 (0.03092515237272403, 'example'),
 (0.024934729909977735, 'services'),
 (0.014620255986541007, 'privacy'),
 (0.014243658634535552, 'account'),
 (0.012995509064479455, 'learn'),
 (0.011380856721559349, 'personal'),
 (0.009703114682017587, 'policy'),
 (0.009595790506993737, 'including')]

20150630:


[(0.05009529551436011, 'information'),
 (0.04395847646116376, 'google'),
 (0.0320063414151115, 'example'),
 (0.024754385894967746, 'services'),
 (0.014637537228131605, 'account'),
 (0.014326215987464084, 'privacy'),
 (0.013745041456304941, 'learn'),
 (0.01115377932530377, 'personal'),
 (0.009537208048941273, 'including'),
 (0.0094075366732092, 'policy')]

20150819:


[(0.04966840798850737, 'information'),
 (0.044448694443797086, 'google'),
 (0.03249770334912015, 'example'),
 (0.024755179089205083, 'services'),
 (0.014950896175783894, 'account'),
 (0.014277650359440812, 'learn'),
 (0.014152781558004784, 'privacy'),
 (0.010980470580612913, 'personal'),
 (0.009486466127467525, 'including'),
 (0.009184004898271527, 'policy')]

20160325:


[(0.04925579599351591, 'information'),
 (0.04478322380819817, 'google'),
 (0.032634316230273956, 'example'),
 (0.02488752723948258, 'services'),
 (0.01520331911370784, 'account'),
 (0.014631543817631985, 'learn'),
 (0.014041077040390648, 'privacy'),
 (0.010872020914438237, 'personal'),
 (0.009447654033509069, 'including'),
 (0.009014802101529865, 'policy')]

20160628:


[(0.04884454326809214, 'information'),
 (0.044999344836953205, 'google'),
 (0.03260673574651408, 'example'),
 (0.025096215588895167, 'services'),
 (0.015396159788374554, 'account'),
 (0.014859391408375586, 'learn'),
 (0.013966540515958631, 'privacy'),
 (0.010819916201129574, 'personal'),
 (0.009424528163765544, 'including'),
 (0.008887956042680402, 'policy')]

20160829:


[(0.04851313499479124, 'information'),
 (0.04507929633925645, 'google'),
 (0.03254089659256503, 'example'),
 (0.025324444791139104, 'services'),
 (0.015527345813476947, 'account'),
 (0.01500604950481723, 'learn'),
 (0.013926964081356307, 'privacy'),
 (0.010792170718511268, 'personal'),
 (0.00942139702985288, 'including'),
 (0.008797615022626428, 'policy')]

20170301:


[(0.04828547056404339, 'information'),
 (0.04506782952072086, 'google'),
 (0.03249356551852848, 'example'),
 (0.025534321028159654, 'services'),
 (0.015610041678110781, 'account'),
 (0.01510014897494476, 'learn'),
 (0.013906017268683775, 'privacy'),
 (0.01077593764133583, 'personal'),
 (0.009427331294944878, 'including'),
 (0.008737692138911743, 'policy')]

20170417:


[(0.04814890240841707, 'information'),
 (0.04504342098486236, 'google'),
 (0.032473391755756614, 'example'),
 (0.02569672174181504, 'services'),
 (0.015657156030327773, 'account'),
 (0.015155350296379978, 'learn'),
 (0.013895086579157659, 'privacy'),
 (0.010765578611032736, 'personal'),
 (0.009435385008846673, 'including'),
 (0.008705624171612546, 'like')]

20171002:


[(0.04808603824669193, 'information'),
 (0.045037431894413046, 'google'),
 (0.032470511457592374, 'example'),
 (0.025788093053724995, 'services'),
 (0.015678759411929984, 'account'),
 (0.015180438252064684, 'learn'),
 (0.013890428980511705, 'privacy'),
 (0.010759967445992955, 'personal'),
 (0.009441128972282536, 'including'),
 (0.008744305853910672, 'like')]

In [17]:
model.gamma_

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [18]:
dim_model = DtmModel(path_to_dtm_binary, corpus, time_seq, num_topics=1,
                 id2word=corpus.dictionary, initialize_lda=True, model='fixed')

In [19]:
document_no = 1 #document 2
topic_no = 0 #topic number 1
time_slice = 0 #time slice 1

type(dim_model.influences_time)
dim_model.influences_time

# for document_no in range(len(corpus)):
# for time_slice in range(len(time_seq)):
#    dim_model.influences_time[time_slice][document_no][topic_no]
    

list

[array([[0.04487017]]),
 array([[0.00755651]]),
 array([[0.01054809]]),
 array([[0.03098739]]),
 array([[0.08948956]]),
 array([[0.00262296]]),
 array([[-0.00572049]]),
 array([[0.02206943]]),
 array([[-0.00018109]]),
 array([[0.04982455]]),
 array([[0.09681206]]),
 array([[0.02833254]]),
 array([[-0.01311693]]),
 array([[-0.02827837]]),
 array([[0.04643593]]),
 array([[0.07417891]]),
 array([[0.04799896]]),
 array([[0.02677942]]),
 array([[0.04160749]]),
 array([[0.03504583]]),
 array([[0.04164879]]),
 array([[0.03966195]]),
 array([[0.03814424]]),
 array([[0.02960172]]),
 array([[0.01487303]]),
 array([[0.00038175]]),
 array([[0.]])]

In [20]:
help(dim_model)

Help on DtmModel in module gensim.models.wrappers.dtmmodel object:

class DtmModel(gensim.utils.SaveLoad)
 |  Python wrapper using `DTM implementation <https://github.com/magsilva/dtm/tree/master/bin>`_.
 |  
 |  Communication between DTM and Python takes place by passing around data files on disk and executing
 |  the DTM binary as a subprocess.
 |  
 |  Warnings
 |  --------
 |  This is **only** python wrapper for `DTM implementation <https://github.com/magsilva/dtm/tree/master/bin>`_,
 |  you need to install original implementation first and pass the path to binary to ``dtm_path``.
 |  
 |  Method resolution order:
 |      DtmModel
 |      gensim.utils.SaveLoad
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(self, dtm_path, corpus=None, time_slices=None, mode='fit', model='dtm', num_topics=100, id2word=None, prefix=None, lda_sequence_min_iter=6, lda_sequence_max_iter=20, lda_max_em_iter=10, alpha=0.01, top_chain_var=0.005, rng_seed=0, initialize_lda=True)
 |

In [ ]:
influences = [round(max(i)[0], 4) for i in dim_model.influences_time]
influences

In [ ]:
from pyecharts import Line

line = Line("Influences")
years = [i for i in range(len(influences))]
line.add("Google's policies", years, influences, mark_point=['max'], mark_point_symbol='arrow')
line

In [23]:
test_documents = [documents[4] for i in range(10)]
test_corpus = DTMcorpus(test_documents)
test_time_seq = [1] * 10
test_dim_model = DtmModel(path_to_dtm_binary, test_corpus, test_time_seq, num_topics=1,
                 id2word=test_corpus.dictionary, initialize_lda=True, model='fixed')

In [24]:
test_dim_model.influences_time

[array([[0.38547742]]),
 array([[0.15435206]]),
 array([[0.05475012]]),
 array([[0.02807272]]),
 array([[0.02779628]]),
 array([[0.02951287]]),
 array([[0.02450806]]),
 array([[0.01139932]]),
 array([[0.00020762]]),
 array([[0.]])]

# Confused

Why `influences_time` varies with exactly **identical** documents?
And it decreases?

# Possible Explanation

`time slice` may be taken into consideration

# According the paper

## Screenshots:

---
<img src="https://ws4.sinaimg.cn/large/006tKfTcgy1g0ogsc25abj30ry05cgmx.jpg" width="400px"/>

---
<img src="https://ws2.sinaimg.cn/large/006tKfTcgy1g0ogziwu7zj30yo07qmyq.jpg" width="400dip"/>

where $\tilde{m}_{t+1}$ stands for the mean value of topic trajectory $\tilde{\beta}_{k, t}$.

In [25]:
another_test_documents = [["前天晚上做梦，梦见和大猫、大儒、小三、静静以及帆神一起在KTV里唱歌。这是个再寻常不过的场景，因为两周以前的周五我们一行六人就一同去唱过歌。但是在梦里，我们以一人唱一小段的方式一起唱的一首歌词很棒、旋律也非常好听的歌，引起了我的注意。梦里的我意识到自己是在做梦了，于是开始在梦里思考，这首好听的歌究竟是显示中存在的歌，还是我的潜意识在梦里自行创作出来的歌呢？如果是后者的话，若将这歌词记录下来岂不妙哉？于是梦里的我经过仔细的思考判断，认为是一首现实中存在的歌，因此记录歌词之事不了了之。"],["醒来之后的我，忆起梦中之事，却无论如何也记不起这首被梦中的我认定是现实中存在的歌究竟叫什么名字。甚至对于梦中隐约记得的旋律，也感觉颇为陌生。这首歌莫不是真是我梦中所作？怀着怅然若失的感觉，我开始仔细回忆梦里的一些细节。最后只记得一星半点：轮到我唱的那一段似乎恰好是副歌部分，而且有一句歌词有“杯中”的字眼，末尾的字不记得是“古”还是“口”了。面对这样的线索，我更惆怅了，因为印象里自己没听过这样的歌曲，可能是真的错失了梦中所作的歌吧！"], ["昨天夜里，躺在床上，像往常一样打开网易云音乐准备边听歌边睡觉的我，突然想起一件至关重要的事情：前天夜里我是听着网易云的私人FM睡觉的！也许梦里的歌就在其中！怀揣着这样的念头，我不停地在听歌记录里翻找符合条件的歌。功夫不负有心人，最后终于找到一首副歌开头部分是“熬到结局，杯中酒剩一口”的歌——音阙诗听的《我已经走到了幻想尽头》。经过反复的播放，我确信这旋律正是梦中的旋律，这首歌正是出现在我梦中的那首歌。\
历经此番寻梦，不由得感叹：网易云音乐，一款能将音乐带到我梦里的播放器；音阙诗听，一个能将歌曲唱到我梦里的音乐社团；《我已经走到了幻想尽头》，一首闯入我梦境的歌。"]]
another_test_corpus = DTMcorpus(another_test_documents)
another_test_time_seq = [1] * len(another_test_documents)
another_test_dim_model = DtmModel(path_to_dtm_binary, another_test_corpus, another_test_time_seq, num_topics=1,
                 id2word=another_test_corpus.dictionary, initialize_lda=True, model='fixed')

In [26]:
another_test_dim_model.influences_time

[array([[0.00486905]]), array([[6.17762782e-05]]), array([[0.]])]

In [27]:
from lxml.html.clean import Cleaner
cleaner = Cleaner(page_structure=True,
                  meta=True,
                  embedded=True,
                  links=True,
                  style=True,
                  processing_instructions=True,
                  inline_style=True,
                  scripts=True,
                  javascript=True,
                  comments=True,
                  frames=True,
                  forms=True,
                  annoying_tags=True,
                  remove_unknown_tags=True,
                  remove_tags=('span', 'font', 'div', 'p')
                 )
test_html = """<script>document.documentElement.className = document.documentElement.className.replace( /(^|\s)client-nojs(\s|$)/, "$1client-js$2" );</script>"""
cleaner.clean_html(test_html)

'<div></div>'

In [28]:
from lxml.html.clean import clean_html
lxml.html.fromstring(clean_html(test_html)).text_content()

''